### PR TITLE
Added example of pure CSS Mouse tracking

### PR DESCRIPTION
**Pull request by Momciloo**
Code example of pure SCSS (CSS) mouse tracking with a possibility to change tracking sensitivity.

### CODE REVIEW

**Comment by KtorZ** [comment]
@Momciloo: Try to keep the alphabetical order ;)

**Comment by Momciloo** [comment]
I think I fixed it now.
This is my first public GitHub contribution, so maybe I missed something.

**Comment by Momciloo** [comment]
I think I fixed it now.
This is my first public GitHub contribution, so maybe I missed something.

**Comment by NamPNQ** [comment]
Merge to one commit will better :D, but it's not a problem, tks you for make a PR :heart:

**Pull request merged**
